#!/bin/bash
echo "###########################
#    Nomrebi.com Parser   #
########################### 
#    ავტორი: Pwn3Xpert    #
# დაბუსტა: git://ghsec-მა #
###########################
"
echo -n "შეიყვანე ნომერი=> "
read number
parse(){
curl 'https://simpleapi.info/apps/numbers-info/info.php' --data number=$number | jq .info.name --raw-output
}
if parse; then
echo ""
else
  echo " [-]=> ვერ მოიძებნა"
fi
